import { PrismaClient } from "@prisma/client";
import bcrypt from "bcrypt";

const prisma = new PrismaClient();
async function main() {
  const user = await prisma.user.upsert({
    where: {
      username: "admin",
    },
    create: {
      username: "admin",
      password: await bcrypt.hash("P@ssW0rd", 10),
    },
    update: {},
  });

  await prisma.participant.createMany({
    data: [
      {
        id: 1,
        name: "Adi Arnawa",
      },
      {
        id: 2,
        name: "Alit Sucipta",
      },
    ],
    skipDuplicates: true,
  });

  const districts = [
    { id: 1, name: "Petang" },
    { id: 2, name: "Abiansemal" },
    { id: 3, name: "Mengwi" },
    { id: 4, name: "Kuta Utara" },
    { id: 5, name: "Kuta Selatan" },
    { id: 6, name: "Kuta" },
  ];

  const villages = [
    { id: 1, name: "Carangsari", districtId: 1 },
    { id: 2, name: "Belok / Sidan", districtId: 1 },
    { id: 3, name: "Sulangai", districtId: 1 },
    { id: 4, name: "Pangsan", districtId: 1 },
    { id: 5, name: "Getasan", districtId: 1 },
    { id: 6, name: "Petang", districtId: 1 },
    { id: 7, name: "Pelaga", districtId: 1 },
    { id: 8, name: "Sibanggede", districtId: 2 },
    { id: 9, name: "Abiansemal", districtId: 2 },
    { id: 10, name: "Punggul", districtId: 2 },
    { id: 11, name: "Mekar Bhuwana", districtId: 2 },
    { id: 12, name: "Mambal", districtId: 2 },
    { id: 13, name: "Sibangkaja", districtId: 2 },
    { id: 14, name: "Blahkiuh", districtId: 2 },
    { id: 15, name: "Abiansemal Dauh Yeh Cani", districtId: 2 },
    { id: 16, name: "Bongkasa Pertiwi", districtId: 2 },
    { id: 17, name: "Angantaka", districtId: 2 },
    { id: 18, name: "Jagapati", districtId: 2 },
    { id: 19, name: "Ayunan", districtId: 2 },
    { id: 20, name: "Bongkasa", districtId: 2 },
    { id: 21, name: "Darmasaba", districtId: 2 },
    { id: 22, name: "Selat", districtId: 2 },
    { id: 23, name: "Sangeh", districtId: 2 },
    { id: 24, name: "Sedang Kaja", districtId: 2 },
    { id: 25, name: "Taman", districtId: 2 },
    { id: 26, name: "Gulingan", districtId: 3 },
    { id: 27, name: "Buduk", districtId: 3 },
    { id: 28, name: "Kuwum", districtId: 3 },
    { id: 29, name: "Mengwi", districtId: 3 },
    { id: 30, name: "Werdhi Bhuwana", districtId: 3 },
    { id: 31, name: "Tumbak Bayuh", districtId: 3 },
    { id: 32, name: "Baha", districtId: 3 },
    { id: 33, name: "Penarungan", districtId: 3 },
    { id: 34, name: "Pererenan", districtId: 3 },
    { id: 35, name: "Cemagi", districtId: 3 },
    { id: 36, name: "Munggu", districtId: 3 },
    { id: 37, name: "Kekeran", districtId: 3 },
    { id: 38, name: "Sobangan", districtId: 3 },
    { id: 39, name: "Mengwitani", districtId: 3 },
    { id: 40, name: "Sembung", districtId: 3 },
    { id: 41, name: "Canggu", districtId: 4 },
    { id: 42, name: "Tibubeneng", districtId: 4 },
    { id: 43, name: "Dalung", districtId: 4 },
    { id: 44, name: "Ungasan", districtId: 5 },
    { id: 45, name: "Kutuh", districtId: 5 },
    { id: 46, name: "Pecatu", districtId: 5 },
    { id: 47, name: "Kerobokan", districtId: 4 },
    { id: 48, name: "Kerobokan Kaja", districtId: 4 },
    { id: 49, name: "Kerobokan Kelod", districtId: 4 },
    { id: 50, name: "Jimbaran", districtId: 5 },
    { id: 51, name: "Benoa", districtId: 5 },
    { id: 52, name: "Tanjung Benoa", districtId: 5 },
    { id: 53, name: "Seminyak", districtId: 6 },
    { id: 54, name: "Legian", districtId: 6 },
    { id: 55, name: "Kuta", districtId: 6 },
    { id: 56, name: "Tuban", districtId: 6 },
    { id: 57, name: "Kedonganan", districtId: 6 },
  ];

  const neighborhoods = [
    { id: 1, name: "Banjar Dinas Telugtug", villageId: 1 },
    { id: 2, name: "Banjar Dinas Beng", villageId: 1 },
    { id: 3, name: "Banjar Dinas Anggungan", villageId: 1 },
    { id: 4, name: "Banjar Dinas Senapan", villageId: 1 },
    { id: 5, name: "Banjar Dinas Pemijian", villageId: 1 },
    { id: 6, name: "Banjar Dinas Bedauh", villageId: 1 },
    { id: 7, name: "Banjar Dinas Mekarsari", villageId: 1 },
    { id: 8, name: "Banjar Dinas Samuan Kawan", villageId: 1 },
    { id: 9, name: "Banjar Dinas Samuan Kangin", villageId: 1 },
    { id: 10, name: "Banjar Dinas Sangut", villageId: 1 },
    { id: 11, name: "Banjar Dinas Penikit", villageId: 2 },
    { id: 12, name: "Banjar Dinas Sidan", villageId: 2 },
    { id: 13, name: "Banjar Dinas Sidan Kawan", villageId: 2 },
    { id: 14, name: "Banjar Dinas Selantang", villageId: 2 },
    { id: 15, name: "Banjar Dinas Belok", villageId: 2 },
    { id: 16, name: "Banjar Dinas Bon", villageId: 2 },
    { id: 17, name: "Banjar Dinas Jempanang", villageId: 2 },
    { id: 18, name: "Banjar Dinas Sekarmukti", villageId: 2 },
    { id: 19, name: "Banjar Dinas Lawak", villageId: 2 },
    { id: 20, name: "Banjar Dinas Sulangai", villageId: 3 },
    { id: 21, name: "Banjar Dinas Wanasari", villageId: 3 },
    { id: 22, name: "Banjar Dinas Wanakeling", villageId: 3 },
    { id: 23, name: "Banjar Dinas Abing", villageId: 3 },
    { id: 24, name: "Banjar Dinas Batulantang", villageId: 3 },
    { id: 25, name: "Banjar Dinas Sandakan", villageId: 3 },
    { id: 26, name: "Banjar Dinas Sandakan Kangin", villageId: 3 },
    { id: 27, name: "Banjar Dinas Sekarmukti", villageId: 4 },
    { id: 28, name: "Banjar Dinas Pangsan Dalem", villageId: 4 },
    { id: 29, name: "Banjar Dinas Kasianan", villageId: 4 },
    { id: 30, name: "Banjar Dinas Pundung", villageId: 4 },
    { id: 31, name: "Banjar Dinas Pangsan Tengah", villageId: 4 },
    { id: 32, name: "Banjar Dinas Ubud", villageId: 5 },
    { id: 33, name: "Banjar Dinas Kauh", villageId: 5 },
    { id: 34, name: "Banjar Dinas Tengah", villageId: 5 },
    { id: 35, name: "Banjar Dinas Buangga", villageId: 5 },
    { id: 36, name: "Banjar Dinas Petang Dalem", villageId: 6 },
    { id: 37, name: "Banjar Dinas Petang", villageId: 6 },
    { id: 38, name: "Banjar Dinas Petang Suci", villageId: 6 },
    { id: 39, name: "Banjar Dinas Kerta", villageId: 6 },
    { id: 40, name: "Banjar Dinas Lipah", villageId: 6 },
    { id: 41, name: "Banjar Dinas Munduk Damping", villageId: 6 },
    { id: 42, name: "Banjar Dinas Angantiga", villageId: 6 },
    { id: 43, name: "Banjar Dinas Pelaga", villageId: 7 },
    { id: 44, name: "Banjar Dinas Bukin", villageId: 7 },
    { id: 45, name: "Banjar Dinas Kiadan", villageId: 7 },
    { id: 46, name: "Banjar Dinas Nungnung", villageId: 7 },
    { id: 47, name: "Banjar Dinas Bukit Munduk Tiying", villageId: 7 },
    { id: 48, name: "Banjar Dinas Auman", villageId: 7 },
    { id: 49, name: "Banjar Dinas Tiying", villageId: 7 },
    { id: 50, name: "Banjar Dinas Semanik", villageId: 7 },
    { id: 51, name: "Banjar Dinas Tinggan", villageId: 7 },
    { id: 52, name: "Banjar Dinas Bantas Kelod", villageId: 8 },
    { id: 53, name: "Banjar Dinas Bantas Kaja", villageId: 8 },
    { id: 54, name: "Banjar Dinas Mengwi", villageId: 8 },
    { id: 55, name: "Banjar Dinas Dualang", villageId: 8 },
    { id: 56, name: "Banjar Dinas Parekan", villageId: 8 },
    { id: 57, name: "Banjar Dinas Busana", villageId: 8 },
    { id: 58, name: "Banjar Dinas Senggu", villageId: 8 },
    { id: 59, name: "Banjar Dinas Tagtag", villageId: 8 },
    { id: 60, name: "Banjar Dinas Srijati", villageId: 8 },
    { id: 61, name: "Banjar Dinas Badung", villageId: 8 },
    { id: 62, name: "Banjar Dinas Pane", villageId: 8 },
    { id: 63, name: "Banjar Dinas Pekandelan", villageId: 8 },
    { id: 64, name: "Banjar Dinas Juwet", villageId: 9 },
    { id: 65, name: "Banjar Dinas Pande", villageId: 9 },
    { id: 66, name: "Banjar Dinas Keraman", villageId: 9 },
    { id: 67, name: "Banjar Dinas Gunung", villageId: 9 },
    { id: 68, name: "Banjar Dinas Aseman", villageId: 9 },
    { id: 69, name: "Banjar Dinas Latusari", villageId: 9 },
    { id: 70, name: "Banjar Dinas Dirgahayu", villageId: 9 },
    { id: 71, name: "Banjar Dinas Purwakerta", villageId: 9 },
    { id: 72, name: "Banjar Dinas Teguan", villageId: 10 },
    { id: 73, name: "Banjar Dinas Padang", villageId: 10 },
    { id: 74, name: "Banjar Dinas Tengah", villageId: 10 },
    { id: 75, name: "Banjar Dinas Trinadi", villageId: 10 },
    { id: 76, name: "Banjar Dinas Kelodan", villageId: 10 },
    { id: 77, name: "Banjar Dinas Samu", villageId: 11 },
    { id: 78, name: "Banjar Dinas Lambing", villageId: 11 },
    { id: 79, name: "Banjar Dinas Bindu", villageId: 11 },
    { id: 80, name: "Banjar Dinas Sigaran", villageId: 11 },
    { id: 81, name: "Banjar Dinas Tingas", villageId: 11 },
    { id: 82, name: "Banjar Dinas Lebah Sari", villageId: 12 },
    { id: 83, name: "Banjar Dinas Undagi", villageId: 12 },
    { id: 84, name: "Banjar Dinas Agung", villageId: 12 },
    { id: 85, name: "Banjar Dinas Trijata", villageId: 12 },
    { id: 86, name: "Banjar Dinas Mambal Kajanan", villageId: 12 },
    { id: 87, name: "Banjar Dinas Gumasih", villageId: 12 },
    { id: 88, name: "Banjar Dinas Umahanyar", villageId: 12 },
    { id: 89, name: "Banjar Dinas Pengiyasan", villageId: 12 },
    { id: 90, name: "Banjar Dinas Semana", villageId: 12 },
    { id: 91, name: "Banjar Dinas Piakan", villageId: 13 },
    { id: 92, name: "Banjar Dinas Sintrig", villageId: 13 },
    { id: 93, name: "Banjar Dinas Lambing", villageId: 13 },
    { id: 94, name: "Banjar Dinas Sangging", villageId: 13 },
    { id: 95, name: "Banjar Dinas Lateng", villageId: 13 },
    { id: 96, name: "Banjar Dinas Tengah", villageId: 13 },
    { id: 97, name: "Banjar Dinas Saren", villageId: 13 },
    { id: 98, name: "Banjar Dinas Pikah", villageId: 14 },
    { id: 99, name: "Banjar Dinas Benekawan", villageId: 14 },
    { id: 100, name: "Banjar Dinas Tengah", villageId: 14 },
    { id: 101, name: "Banjar Dinas Dlodpasar", villageId: 14 },
    { id: 102, name: "Banjar Dinas Kembangsari", villageId: 14 },
    { id: 103, name: "Banjar Dinas Ulapan I", villageId: 14 },
    { id: 104, name: "Banjar Dinas Ulapan II", villageId: 14 },
    { id: 105, name: "Banjar Dinas Tegal", villageId: 15 },
    { id: 106, name: "Banjar Dinas Belawan", villageId: 15 },
    { id: 107, name: "Banjar Dinas Batanbuah", villageId: 15 },
    { id: 108, name: "Banjar Dinas An", villageId: 15 },
    { id: 109, name: "Banjar Dinas Kedampal", villageId: 15 },
    { id: 110, name: "Banjar Dinas Sempidi", villageId: 15 },
    { id: 111, name: "Banjar Dinas Karang Dalem I", villageId: 16 },
    { id: 112, name: "Banjar Dinas Karang Dalem II", villageId: 16 },
    { id: 113, name: "Banjar Dinas Tegal Kuning", villageId: 16 },
    { id: 114, name: "Banjar Dinas Dalem", villageId: 17 },
    { id: 115, name: "Banjar Dinas Puseh", villageId: 17 },
    { id: 116, name: "Banjar Dinas Desa", villageId: 17 },
    { id: 117, name: "Banjar Dinas Kekeran", villageId: 17 },
    { id: 118, name: "Banjar Dinas Sibang", villageId: 18 },
    { id: 119, name: "Banjar Dinas Pasek", villageId: 18 },
    { id: 120, name: "Banjar Dinas Kemulan", villageId: 18 },
    { id: 121, name: "Banjar Dinas Jabejero", villageId: 18 },
    { id: 122, name: "Banjar Dinas Badung", villageId: 19 },
    { id: 123, name: "Banjar Dinas Badung Tengah", villageId: 19 },
    { id: 124, name: "Banjar Dinas Geria", villageId: 19 },
    { id: 125, name: "Banjar Dinas Ambengan", villageId: 19 },
    { id: 126, name: "Banjar Dinas Kedewatan", villageId: 20 },
    { id: 127, name: "Banjar Dinas Pengb. Sari", villageId: 20 },
    { id: 128, name: "Banjar Dinas Pengembungan", villageId: 20 },
    { id: 129, name: "Banjar Dinas Tanggayuda", villageId: 20 },
    { id: 130, name: "Banjar Dinas Sayan Agung", villageId: 20 },
    { id: 131, name: "Banjar Dinas Sayan Tua", villageId: 20 },
    { id: 132, name: "Banjar Dinas Kambang", villageId: 20 },
    { id: 133, name: "Banjar Dinas Teguan", villageId: 20 },
    { id: 134, name: "Banjar Dinas Kutaraga", villageId: 20 },
    { id: 135, name: "Banjar Dinas Tohpati", villageId: 20 },
    { id: 136, name: "Banjar Dinas Bersih", villageId: 21 },
    { id: 137, name: "Banjar Dinas Taman", villageId: 21 },
    { id: 138, name: "Banjar Dinas Cabe", villageId: 21 },
    { id: 139, name: "Banjar Dinas Menesa", villageId: 21 },
    { id: 140, name: "Banjar Dinas Darmasaba", villageId: 21 },
    { id: 141, name: "Banjar Dinas Penenjoan", villageId: 21 },
    { id: 142, name: "Banjar Dinas Telanga", villageId: 21 },
    { id: 143, name: "Banjar Dinas Tengah", villageId: 21 },
    { id: 144, name: "Banjar Dinas Baler Pasar", villageId: 21 },
    { id: 145, name: "Banjar Dinas Bucu", villageId: 21 },
    { id: 146, name: "Banjar Dinas Gulingan", villageId: 21 },
    { id: 147, name: "Banjar Dinas Umahanyar", villageId: 21 },
    { id: 148, name: "Banjar Dinas Selat Anyar", villageId: 22 },
    { id: 149, name: "Banjar Dinas Selat", villageId: 22 },
    { id: 150, name: "Banjar Dinas Tegal", villageId: 22 },
    { id: 151, name: "Banjar Dinas Mekarsari", villageId: 22 },
    { id: 152, name: "Banjar Dinas Pemijian", villageId: 23 },
    { id: 153, name: "Banjar Dinas Sibang", villageId: 23 },
    { id: 154, name: "Banjar Dinas Brahmana", villageId: 23 },
    { id: 155, name: "Banjar Dinas Mulukbabi", villageId: 23 },
    { id: 156, name: "Banjar Dinas Batusari", villageId: 23 },
    { id: 157, name: "Banjar Dinas Pacung", villageId: 23 },
    { id: 158, name: "Banjar Dinas Tegal Gerana", villageId: 23 },
    { id: 159, name: "Banjar Dinas Batulumbang", villageId: 23 },
    { id: 160, name: "Banjar Dinas Piakan", villageId: 24 },
    { id: 161, name: "Banjar Dinas Sintrig", villageId: 24 },
    { id: 162, name: "Banjar Dinas Lambing", villageId: 24 },
    { id: 163, name: "Banjar Dinas Sangging", villageId: 24 },
    { id: 164, name: "Banjar Dinas Lateng", villageId: 24 },
    { id: 165, name: "Banjar Dinas Tengah", villageId: 24 },
    { id: 166, name: "Banjar Dinas Saren", villageId: 24 },
    { id: 167, name: "Banjar Dinas Tabah", villageId: 25 },
    { id: 168, name: "Banjar Dinas Mambul", villageId: 25 },
    { id: 169, name: "Banjar Dinas Sukajati", villageId: 25 },
    { id: 170, name: "Banjar Dinas Pegingan", villageId: 25 },
    { id: 171, name: "Banjar Dinas Tebo Jero", villageId: 25 },
    { id: 172, name: "Banjar Dinas Gunung", villageId: 25 },
    { id: 173, name: "Banjar Dinas Raketan", villageId: 25 },
    { id: 174, name: "Banjar Dinas Delod Pasar", villageId: 25 },
    { id: 175, name: "Banjar Dinas Batubayan", villageId: 25 },
    { id: 176, name: "Banjar Dinas Ketogan", villageId: 25 },
    { id: 177, name: "Banjar Dinas Jempeng", villageId: 25 },
    { id: 178, name: "Banjar Dinas Jempeng Kauh", villageId: 25 },
    { id: 179, name: "Banjar Dinas Lebah Sari", villageId: 26 },
    { id: 180, name: "Banjar Dinas Tengah Kaler", villageId: 26 },
    { id: 181, name: "Banjar Dinas Tengah Kelod", villageId: 26 },
    { id: 182, name: "Banjar Dinas Ulun Uma Wedan", villageId: 26 },
    { id: 183, name: "Banjar Dinas Dharmayasa", villageId: 26 },
    { id: 184, name: "Banjar Dinas Angkeb Canging", villageId: 26 },
    { id: 185, name: "Banjar Dinas Babakan Kawan", villageId: 26 },
    { id: 186, name: "Banjar Dinas Sedahan", villageId: 26 },
    { id: 187, name: "Banjar Dinas Ulun Uma Badung", villageId: 26 },
    { id: 188, name: "Banjar Dinas Babakan Kangin", villageId: 26 },
    { id: 189, name: "Banjar Dinas Munggu", villageId: 26 },
    { id: 190, name: "Banjar Dinas Batulumbung", villageId: 26 },
    { id: 191, name: "Banjar Dinas Badung", villageId: 26 },
    { id: 192, name: "Banjar Dinas Gunung", villageId: 27 },
    { id: 193, name: "Banjar Dinas Umakepuh", villageId: 27 },
    { id: 194, name: "Banjar Dinas Umacandi", villageId: 27 },
    { id: 195, name: "Banjar Dinas Umategal", villageId: 27 },
    { id: 196, name: "Banjar Dinas Pasekan", villageId: 27 },
    { id: 197, name: "Banjar Dinas Sengguan", villageId: 27 },
    { id: 198, name: "Banjar Dinas Tengah", villageId: 27 },
    { id: 199, name: "Banjar Dinas Kaja", villageId: 27 },
    { id: 200, name: "Banjar Dinas Tampakkerep", villageId: 27 },
    { id: 201, name: "Banjar Dinas Bernasi", villageId: 27 },
    { id: 202, name: "Banjar Dinas Nyelati", villageId: 28 },
    { id: 203, name: "Banjar Dinas Balangan Kangin", villageId: 28 },
    { id: 204, name: "Banjar Dinas Kuwum", villageId: 28 },
    { id: 205, name: "Banjar Dinas Balangan", villageId: 28 },
    { id: 206, name: "Banjar Dinas Batu", villageId: 29 },
    { id: 207, name: "Banjar Dinas Gambang", villageId: 29 },
    { id: 208, name: "Banjar Dinas Munggu", villageId: 29 },
    { id: 209, name: "Banjar Dinas Pandéan", villageId: 29 },
    { id: 210, name: "Banjar Dinas Pandé", villageId: 29 },
    { id: 211, name: "Banjar Dinas Peregae", villageId: 29 },
    { id: 212, name: "Banjar Dinas Lebah Pangkung", villageId: 29 },
    { id: 213, name: "Banjar Dinas Pengiasan", villageId: 29 },
    { id: 214, name: "Banjar Dinas Alangkajeng", villageId: 29 },
    { id: 215, name: "Banjar Dinas Serangan", villageId: 29 },
    { id: 216, name: "Banjar Dinas Delod Bale Agung", villageId: 29 },
    { id: 217, name: "Banjar Dinas Binong", villageId: 30 },
    { id: 218, name: "Banjar Dinas Sayan Baleran", villageId: 30 },
    { id: 219, name: "Banjar Dinas Sayan Delodan", villageId: 30 },
    { id: 220, name: "Banjar Dinas Sunia", villageId: 30 },
    { id: 221, name: "Banjar Dinas Denkayu Baleran", villageId: 30 },
    { id: 222, name: "Banjar Dinas Denkayu Delodan", villageId: 30 },
    { id: 223, name: "Banjar Dinas Gunung Pande", villageId: 31 },
    { id: 224, name: "Banjar Dinas Datengan", villageId: 31 },
    { id: 225, name: "Banjar Dinas Jerowan", villageId: 31 },
    { id: 226, name: "Banjar Dinas Pemabatan", villageId: 31 },
    { id: 227, name: "Banjar Dinas Dangin Sema", villageId: 31 },
    { id: 228, name: "Banjar Dinas Kelepekan", villageId: 31 },
    { id: 229, name: "Banjar Dinas Tiying Tutul", villageId: 31 },
    { id: 230, name: "Banjar Dinas Bedil", villageId: 32 },
    { id: 231, name: "Banjar Dinas Gegaran", villageId: 32 },
    { id: 232, name: "Banjar Dinas Kedua", villageId: 32 },
    { id: 233, name: "Banjar Dinas Pengabetan", villageId: 32 },
    { id: 234, name: "Banjar Dinas Busana Kelod", villageId: 32 },
    { id: 235, name: "Banjar Dinas Busana Kaja", villageId: 32 },
    { id: 236, name: "Banjar Dinas Cengkok", villageId: 32 },
    { id: 237, name: "Banjar Dinas Bantas", villageId: 33 },
    { id: 238, name: "Banjar Dinas Umopoh", villageId: 33 },
    { id: 239, name: "Banjar Dinas Dajan Peken", villageId: 33 },
    { id: 240, name: "Banjar Dinas Bangkiangsidem", villageId: 33 },
    { id: 241, name: "Banjar Dinas Dauh Peken", villageId: 33 },
    { id: 242, name: "Banjar Dinas Dangin Peken", villageId: 33 },
    { id: 243, name: "Banjar Dinas Cemenggon", villageId: 33 },
    { id: 244, name: "Banjar Dinas Guming", villageId: 33 },
    { id: 245, name: "Banjar Dinas Umahanyar", villageId: 33 },
    { id: 246, name: "Banjar Dinas Sengguan", villageId: 33 },
    { id: 247, name: "Banjar Dinas Blungbang", villageId: 33 },
    { id: 248, name: "Banjar Dinas Pengembungan", villageId: 34 },
    { id: 249, name: "Banjar Dinas Delodpadonan", villageId: 34 },
    { id: 250, name: "Banjar Dinas Batu", villageId: 34 },
    { id: 251, name: "Banjar Dinas Jempinis", villageId: 34 },
    { id: 252, name: "Banjar Dinas Kangkang", villageId: 34 },
    { id: 253, name: "Banjar Dinas Tiying Tutul", villageId: 34 },
    { id: 254, name: "Banjar Dinas Batan Tanjung", villageId: 35 },
    { id: 255, name: "Banjar Dinas Bale Agung", villageId: 35 },
    { id: 256, name: "Banjar Dinas Sengguan", villageId: 35 },
    { id: 257, name: "Banjar Dinas Petapan", villageId: 35 },
    { id: 258, name: "Banjar Dinas Mengenin", villageId: 35 },
    { id: 259, name: "Banjar Dinas Seseh", villageId: 35 },
    { id: 260, name: "Banjar Dinas Sogsogan", villageId: 35 },
    { id: 261, name: "Banjar Dinas Pengayehan", villageId: 35 },
    { id: 262, name: "Banjar Dinas Sangiangan", villageId: 35 },
    { id: 263, name: "Banjar Dinas Tangkeban", villageId: 35 },
    { id: 264, name: "Banjar Dinas Keliki", villageId: 35 },
    { id: 265, name: "Banjar Dinas Kaja Kangin", villageId: 35 },
    { id: 266, name: "Banjar Dinas Pemaron", villageId: 36 },
    { id: 267, name: "Banjar Dinas Pemaron Delodan", villageId: 36 },
    { id: 268, name: "Banjar Dinas Pande Pemaron", villageId: 36 },
    { id: 269, name: "Banjar Dinas Pengayehan", villageId: 36 },
    { id: 270, name: "Banjar Dinas Badung", villageId: 36 },
    { id: 271, name: "Banjar Dinas Gambang", villageId: 36 },
    { id: 272, name: "Banjar Dinas Pandean", villageId: 36 },
    { id: 273, name: "Banjar Dinas Kerobokan", villageId: 36 },
    { id: 274, name: "Banjar Dinas Pasekan", villageId: 36 },
    { id: 275, name: "Banjar Dinas Pemabatan", villageId: 36 },
    { id: 276, name: "Banjar Dinas Sedahan", villageId: 36 },
    { id: 277, name: "Banjar Dinas Dukuh Sengguan", villageId: 36 },
    { id: 278, name: "Banjar Dinas Dukuh Pandean", villageId: 36 },
    { id: 279, name: "Banjar Dinas Gelagah Puwun", villageId: 37 },
    { id: 280, name: "Banjar Dinas Delod Sema", villageId: 37 },
    { id: 281, name: "Banjar Dinas Dangin Pangkung", villageId: 37 },
    { id: 282, name: "Banjar Dinas Sangiang", villageId: 37 },
    { id: 283, name: "Banjar Dinas Penyaringan", villageId: 37 },
    { id: 284, name: "Banjar Dinas Delod Yeh", villageId: 37 },
    { id: 285, name: "Banjar Dinas Tauman", villageId: 37 },
    { id: 286, name: "Banjar Dinas Dukuh Mancos", villageId: 38 },
    { id: 287, name: "Banjar Dinas Tegalnarung", villageId: 38 },
    { id: 288, name: "Banjar Dinas Tengah", villageId: 38 },
    { id: 289, name: "Banjar Dinas Selat", villageId: 38 },
    { id: 290, name: "Banjar Dinas Panca Warga", villageId: 39 },
    { id: 291, name: "Banjar Dinas Pupuan", villageId: 39 },
    { id: 292, name: "Banjar Dinas Pengadangan", villageId: 39 },
    { id: 293, name: "Banjar Dinas Selat", villageId: 39 },
    { id: 294, name: "Banjar Dinas Menak", villageId: 39 },
    { id: 295, name: "Banjar Dinas Kelod Kauh", villageId: 39 },
    { id: 296, name: "Banjar Dinas Dajan Peken", villageId: 39 },
    { id: 297, name: "Banjar Dinas Mengwitani", villageId: 39 },
    { id: 298, name: "Banjar Dinas Lebah Gunung", villageId: 39 },
    { id: 299, name: "Banjar Dinas Jumpayah", villageId: 39 },
    { id: 300, name: "Banjar Dinas Sila Dharma", villageId: 39 },
    { id: 301, name: "Banjar Dinas Nyuh Gading", villageId: 39 },
    { id: 302, name: "Banjar Dinas Culag Calig", villageId: 39 },
    { id: 303, name: "Banjar Dinas Karangenjung Shanti", villageId: 40 },
    { id: 304, name: "Banjar Dinas Karangenjung Bhakti", villageId: 40 },
    { id: 305, name: "Banjar Dinas Dajan Peken", villageId: 40 },
    { id: 306, name: "Banjar Dinas Pasekan", villageId: 40 },
    { id: 307, name: "Banjar Dinas Tauman", villageId: 40 },
    { id: 308, name: "Banjar Dinas Belang", villageId: 40 },
    { id: 309, name: "Banjar Dinas Tegal", villageId: 40 },
    { id: 310, name: "Banjar Dinas Pempatan", villageId: 40 },
    { id: 311, name: "Banjar Dinas Dangin Bingin", villageId: 40 },
    { id: 312, name: "Banjar Dinas Anyar", villageId: 40 },
    { id: 313, name: "Banjar Dinas Padang Tawang", villageId: 41 },
    { id: 314, name: "Banjar Dinas Babakan", villageId: 41 },
    { id: 315, name: "Banjar Dinas Uma Buluh", villageId: 41 },
    { id: 316, name: "Banjar Dinas Kayutulang", villageId: 41 },
    { id: 317, name: "Banjar Dinas Pipitan", villageId: 41 },
    { id: 318, name: "Banjar Dinas Padang Linjong", villageId: 41 },
    { id: 319, name: "Banjar Dinas Canggu", villageId: 41 },
    { id: 320, name: "Banjar Dinas Dama", villageId: 42 },
    { id: 321, name: "Banjar Dinas Dawas", villageId: 42 },
    { id: 322, name: "Banjar Dinas Tibubeneng", villageId: 42 },
    { id: 323, name: "Banjar Dinas Kulibul Kangin", villageId: 42 },
    { id: 324, name: "Banjar Dinas Kulibul Kawan", villageId: 42 },
    { id: 325, name: "Banjar Dinas Aseman Kangin", villageId: 42 },
    { id: 326, name: "Banjar Dinas Aseman Kawan", villageId: 42 },
    { id: 327, name: "Banjar Dinas Tandeg", villageId: 42 },
    { id: 328, name: "Banjar Dinas Pelambingan", villageId: 42 },
    { id: 329, name: "Banjar Dinas Tegalgundul", villageId: 42 },
    { id: 330, name: "Banjar Dinas Berawa", villageId: 42 },
    { id: 331, name: "Banjar Dinas Canggu Permai", villageId: 42 },
    { id: 332, name: "Br Dinas Krisnantara", villageId: 42 },
    { id: 333, name: "Banjar Dinas Bhineka Nusa Kauh", villageId: 43 },
    { id: 334, name: "Banjar Dinas Bhineka Nusa Kangin", villageId: 43 },
    { id: 335, name: "Banjar Dinas Campaun Asri Kangin", villageId: 43 },
    { id: 336, name: "Banjar Dinas Campuan Asri Kauh", villageId: 43 },
    { id: 337, name: "Banjar Dinas Celuk", villageId: 43 },
    { id: 338, name: "Banjar Dinas Cepaka", villageId: 43 },
    { id: 339, name: "Banjar Dinas Dukuh", villageId: 43 },
    { id: 340, name: "Banjar Dinas Gaji", villageId: 43 },
    { id: 341, name: "Banjar Dinas Kaja", villageId: 43 },
    { id: 342, name: "Banjar Dinas Kung", villageId: 43 },
    { id: 343, name: "Banjar Dinas Kwanji", villageId: 43 },
    { id: 344, name: "Banjar Dinas Lebak", villageId: 43 },
    { id: 345, name: "Banjar Dinas Linggabumi", villageId: 43 },
    { id: 346, name: "Banjar Dinas Padangbali", villageId: 43 },
    { id: 347, name: "Banjar Dinas Pegending", villageId: 43 },
    { id: 348, name: "Banjar Dinas Pendem", villageId: 43 },
    { id: 349, name: "Banjar Dinas Penglian", villageId: 43 },
    { id: 350, name: "Banjar Dinas Taman Tirta", villageId: 43 },
    { id: 351, name: "Banjar Dinas Tegal Luwih", villageId: 43 },
    { id: 352, name: "Banjar Dinas Tegaljaya", villageId: 43 },
    { id: 353, name: "Banjar Dinas Tegeh", villageId: 43 },
    { id: 354, name: "Banjar Dinas Tuka", villageId: 43 },
    { id: 355, name: "Banjar Dinas Untal-Untal", villageId: 43 },
    { id: 356, name: "Banjar Dinas Kangin", villageId: 44 },
    { id: 357, name: "Banjar Dinas Kauh", villageId: 44 },
    { id: 358, name: "Banjar Dinas Kelod", villageId: 44 },
    { id: 359, name: "Banjar Dinas Santhi Karya", villageId: 44 },
    { id: 360, name: "Banjar Dinas Giri Dharma", villageId: 44 },
    { id: 361, name: "Banjar Dinas Wana Giri", villageId: 44 },
    { id: 362, name: "Banjar Dinas Sari Karya", villageId: 44 },
    { id: 363, name: "Banjar Dinas Bakung Sari", villageId: 44 },
    { id: 364, name: "Banjar Dinas Kertha Lestari", villageId: 44 },
    { id: 365, name: "Banjar Dinas Wijaya Kusuma", villageId: 44 },
    { id: 366, name: "Banjar Dinas Werdhi Kosala", villageId: 44 },
    { id: 367, name: "Banjar Dinas Mekar Sari", villageId: 44 },
    { id: 368, name: "Banjar Dinas Angas Sari", villageId: 44 },
    { id: 369, name: "Banjar Dinas Langui", villageId: 44 },
    { id: 370, name: "Banjar Dinas Kaja Jati", villageId: 45 },
    { id: 371, name: "Banjar Dinas Jaba Pura", villageId: 45 },
    { id: 372, name: "Banjar Dinas Petangan", villageId: 45 },
    { id: 373, name: "Banjar Dinas Pantigiri", villageId: 45 },
    { id: 374, name: "Banjar Dinas Kangin", villageId: 46 },
    { id: 375, name: "Banjar Dinas Tambyak", villageId: 46 },
    { id: 376, name: "Banjar Dinas Giri Sari", villageId: 46 },
    { id: 377, name: "Banjar Dinas Tengah", villageId: 46 },
    { id: 378, name: "Banjar Dinas Karang Boma", villageId: 46 },
    { id: 379, name: "Banjar Dinas Suluban", villageId: 46 },
    { id: 380, name: "Banjar Dinas Kauh", villageId: 46 },
    { id: 381, name: "Banjar Dinas Labuhan Sait", villageId: 46 },
    { id: 382, name: "Banjar Dinas Buana Sari", villageId: 46 },
    { id: 383, name: "Lingkungan Kesambi", villageId: 47 },
    { id: 384, name: "Lingkungan Peliatan", villageId: 47 },
    { id: 385, name: "Lingkungan Padang", villageId: 47 },
    { id: 386, name: "Lingkungan Anyar Kelod", villageId: 47 },
    { id: 387, name: "Lingkungan Anyar Kaja", villageId: 47 },
    { id: 388, name: "Lingkungan Silayukti", villageId: 47 },
    { id: 389, name: "Lingkungan Gede", villageId: 47 },
    { id: 390, name: "Lingkungan Tegeh", villageId: 47 },
    { id: 391, name: "Lingkungan Kancil", villageId: 47 },
    { id: 392, name: "Lingkungan Campuan", villageId: 47 },
    { id: 393, name: "Lingkungan Batubidak", villageId: 48 },
    { id: 394, name: "Lingkungan Beluran", villageId: 48 },
    { id: 395, name: "Lingkungan Petingan", villageId: 48 },
    { id: 396, name: "Lingkungan Muding Tengah", villageId: 48 },
    { id: 397, name: "Lingkungan Muding Kaja", villageId: 48 },
    { id: 398, name: "Lingkungan Muding Kelod", villageId: 48 },
    { id: 399, name: "Lingkungan Muding Mekar", villageId: 48 },
    { id: 400, name: "Lingkungan Batuculung", villageId: 48 },
    { id: 401, name: "Lingkungan Babakan", villageId: 48 },
    { id: 402, name: "Lingkungan Jambe", villageId: 48 },
    { id: 403, name: "Lingkungan Gadon", villageId: 48 },
    { id: 404, name: "Lingkungan PadangLestari", villageId: 48 },
    { id: 405, name: "Lingkungan Tegal Sari", villageId: 48 },
    { id: 406, name: "Lingkungan Tegal Permai", villageId: 48 },
    { id: 407, name: "Lingkungan Surya Bhuana", villageId: 48 },
    { id: 408, name: "Lingkungan Wira Bhuana", villageId: 48 },
    { id: 409, name: "Lingkungan Blubuh Sari", villageId: 48 },
    { id: 410, name: "Lingkungan Bhuana Asri", villageId: 48 },
    { id: 411, name: "Lingkungan Bhuana Graha", villageId: 48 },
    { id: 412, name: "Lingkungan Bhuana Shanti", villageId: 48 },
    { id: 413, name: "Lingkungan Bumi Kerta", villageId: 48 },
    { id: 414, name: "Lingkungan Bumi Mekar Sari", villageId: 48 },
    { id: 415, name: "Lingkungan Bhineka Asri", villageId: 48 },
    { id: 416, name: "Lingkungan Semer", villageId: 49 },
    { id: 417, name: "Lingkungan Umalas Kangin", villageId: 49 },
    { id: 418, name: "Lingkungan Umalas Kauh", villageId: 49 },
    { id: 419, name: "Lingkungan Batubelig", villageId: 49 },
    { id: 420, name: "Lingkungan Taman", villageId: 49 },
    { id: 421, name: "Lingkungan Taman Merthanadi", villageId: 49 },
    { id: 422, name: "Lingkungan Pengubengan Kangin", villageId: 49 },
    { id: 423, name: "Lingkungan Pengubengan Kauh", villageId: 49 },
    { id: 424, name: "Lingkungan Pengipian", villageId: 49 },
    { id: 425, name: "Lingkungan Kuwum", villageId: 49 },
    { id: 426, name: "Lingkungan Umasari", villageId: 49 },
    { id: 427, name: "Lingkungan Dukuh Sari", villageId: 49 },
    { id: 428, name: "Lingkungan Batubelig Kangin", villageId: 49 },
    { id: 429, name: "Lingkungan Ubung", villageId: 50 },
    { id: 430, name: "Lingkungan Pantai Sari", villageId: 50 },
    { id: 431, name: "Lingkungan Menega", villageId: 50 },
    { id: 432, name: "Lingkungan Pesalakan", villageId: 50 },
    { id: 433, name: "Lingkungan Teba", villageId: 50 },
    { id: 434, name: "Lingkungan Jerokuta", villageId: 50 },
    { id: 435, name: "Lingkungan Kalanganyar", villageId: 50 },
    { id: 436, name: "Lingkungan Tegal", villageId: 50 },
    { id: 437, name: "Lingkungan Perarudan", villageId: 50 },
    { id: 438, name: "Lingkungan Cenggiling", villageId: 50 },
    { id: 439, name: "Lingkungan Taman Griya", villageId: 50 },
    { id: 440, name: "Lingkungan Anggaswara", villageId: 50 },
    { id: 441, name: "Lingkungan Mekar Sari", villageId: 50 },
    { id: 442, name: "Lingkungan Bhuana Gubug", villageId: 50 },
    { id: 443, name: "Lingkungan Terora", villageId: 51 },
    { id: 444, name: "Lingkungan Celuk", villageId: 51 },
    { id: 445, name: "Lingkungan Peken", villageId: 51 },
    { id: 446, name: "Lingkungan Penyarikan", villageId: 51 },
    { id: 447, name: "Lingkungan Menesa", villageId: 51 },
    { id: 448, name: "Lingkungan Sawangan", villageId: 51 },
    { id: 449, name: "Lingkungan Ancak", villageId: 51 },
    { id: 450, name: "Lingkungan Wisma Nusa Permai", villageId: 51 },
    { id: 451, name: "Lingkungan Bualu Indah", villageId: 51 },
    { id: 452, name: "Lingkungan Permata Nusa Dua", villageId: 51 },
    { id: 453, name: "Lingkungan Pande", villageId: 51 },
    { id: 454, name: "Lingkungan Bualu", villageId: 51 },
    { id: 455, name: "Lingkungan Bale Kembar", villageId: 51 },
    { id: 456, name: "Lingkungan Mumbul", villageId: 51 },
    { id: 457, name: "Lingkungan Puri Nusa Dua", villageId: 51 },
    { id: 458, name: "Lingkungan Peminge", villageId: 51 },
    { id: 459, name: "Lingkungan Anyar", villageId: 52 },
    { id: 460, name: "Lingkungan Kertha Pascima", villageId: 52 },
    { id: 461, name: "Lingkungan Panca Bhineka", villageId: 52 },
    { id: 462, name: "Lingkungan Tengah", villageId: 52 },
    { id: 463, name: "Lingkungan Purwa Santhi", villageId: 52 },
    { id: 464, name: "Lingkungan Tengkulung", villageId: 52 },
    { id: 465, name: "Lingkungan Basangkasa", villageId: 53 },
    { id: 466, name: "Lingkungan Seminyak", villageId: 53 },
    { id: 467, name: "Lingkungan Legian Kaja", villageId: 54 },
    { id: 468, name: "Lingkungan Legian Tengah", villageId: 54 },
    { id: 469, name: "Lingkungan Legian Kelod", villageId: 54 },
    { id: 470, name: "Lingkungan Abianbase", villageId: 55 },
    { id: 471, name: "Lingkungan Pelasa", villageId: 55 },
    { id: 472, name: "Lingkungan Pering", villageId: 55 },
    { id: 473, name: "Lingkungan Pemamoran", villageId: 55 },
    { id: 474, name: "Lingkungan Temacun", villageId: 55 },
    { id: 475, name: "Lingkungan Pande Mas", villageId: 55 },
    { id: 476, name: "Lingkungan Pengabetan", villageId: 55 },
    { id: 477, name: "Lingkungan Jaba Jero", villageId: 55 },
    { id: 478, name: "Lingkungan Buni", villageId: 55 },
    { id: 479, name: "Lingkungan Tegal", villageId: 55 },
    { id: 480, name: "Lingkungan Anyar", villageId: 55 },
    { id: 481, name: "Lingkungan Segara", villageId: 55 },
    { id: 482, name: "Lingkungan Teba Sari", villageId: 55 },
    { id: 483, name: "Lingkungan Pesalakan", villageId: 56 },
    { id: 484, name: "Lingkungan Tuban Griya", villageId: 56 },
    { id: 485, name: "Lingkungan Kelan Desa", villageId: 56 },
    { id: 486, name: "Lingkungan Kelan Abian", villageId: 56 },
    { id: 487, name: "Lingkungan Pasek", villageId: 57 },
    { id: 488, name: "Lingkungan Pengenderan", villageId: 57 },
    { id: 489, name: "Lingkungan Ketapang", villageId: 57 },
    { id: 490, name: "Lingkungan Anyar Gede", villageId: 57 },
    { id: 491, name: "Lingkungan Kerthayasa", villageId: 57 },
    { id: 492, name: "Lingkungan Kubu Alit", villageId: 57 },
  ];

  for (let district of districts) {
    await prisma.district.upsert({
      where: {
        id: district.id,
      },
      create: {
        id: district.id,
        name: district.name,
      },
      update: {},
    });
  }

  for (let village of villages) {
    await prisma.village.upsert({
      where: {
        id: village.id,
      },
      create: {
        id: village.id,
        name: village.name,
        districtId: village.districtId,
      },
      update: {},
    });
  }

  for (let neighborhood of neighborhoods) {
    await prisma.neighborhood.upsert({
      where: {
        id: neighborhood.id,
      },
      create: {
        id: neighborhood.id,
        name: neighborhood.name,
        villageId: neighborhood.villageId,
      },
      update: {},
    });
  }

  console.log(user);
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
